jailServer: "MAIN"
kickMessage: "§aCouldn't connect to Jail-Server!"
fallbackKick: true
sql:
  host: "localhost"
  database: "database"
  username: "root"
  password: "root"
  useSSL: true
  datasource: com.mysql.cj.jdbc.Driver
  blocks: "JailBlocks"
  players: "JailPlayers"
  history: "JailHistory"